image: node:alpine

stages:
  - dev
  # - test
  # - build

dev:
  stage: dev
  script:
    - npm run dev
  only:
    - master

# test:
#   stage: test
#   script:
#     - npm run test
#   only:
#     - master

# build:
#   stage: build
#   script:
#     - npm run build
#   only:
#     - master
