version: '3.0'

services:
    myapp:
        container_name: ${CONTAINER_NAME}
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${CONTAINER_PORT}:80
